[phases.build]
cmds = [
  "DATABASE_URL='postgresql://placeholder:placeholder@localhost:5432/postgres' npm ci && DATABASE_URL='postgresql://placeholder:placeholder@localhost:5432/postgres' npx prisma generate"
]

[start]
cmd = "npm start"
